### ISSUE TITLE
Remove calendar and clock icons from blog entry list

### ISSUE THREAD

**Issue by keybatte** [Everything-Explained/web-client#18]
- try removing the calender and clock icons in blog section (b.s)

**Comment by Jaeiya** [comment]
A lot of designs (when displaying time information) use a clock and calendar icon to help people understand what the numbers mean at a glance. I'm curious why you want them removed.

**Comment by keybatte** [comment]
Fair, I imagined it would still be understandable at a glance without them. Makes that space look more minimal and to the point!

**Comment by Jaeiya** [comment]
The blog entry list is already quite minimal as it is, I don't feel like that's enough of a reason to remove the icons at this point in time. I'll black box this though so if need be, we can revisit it later.
