### ISSUE TITLE
Change the brown highlight from paragraph blocks to gray

### ISSUE THREAD

**Issue by keybatte** [Everything-Explained/web-client#19]
- the brown highlight when clicking a section, change to a tad lighter gray for the highlight, than the non-highlighted gray for subtlety in b.s (+ three foundational colors are the maximum in marketing when utilized for the most notable sections. And since the backdrop for the whole website it a dark gray, every colors stands out more)

**Comment by Jaeiya** [comment]
The brown highlight (chocolate) actually has significance to the levels of information that Ethan created. Unless for some reason that color becomes a marketing issue, we can revisit this issue.
