### ISSUE TITLE
Prevent head blog image from being inserted into paragraph blocks

### ISSUE THREAD

**Issue by keybatte** [Everything-Explained/web-client#21]
- If a photo is used before the big header of every blog post, try removing the box around the photo, and leave the box for just the paragraph under the photo. (The rest of the blog still having the boxes)

**Comment by Jaeiya** [comment]
This is something I want to fix. The way it works right now, the image is just compiled from markdown in a predefined format, which unfortunately puts it inside of the following paragraph element. I'll need more input from Ethan to move this forward though, cause I don't know how often he'll want to embed an image and he may want an image to be along side the text in some cases....there's a lot of caveats to think about this.

If the blog is going to include a header image no matter what, then I definitely do want to address this.
