### ISSUE TITLE
Change box-shadow under paragraph blocks to blend better

### ISSUE THREAD

**Issue by keybatte** [Everything-Explained/web-client#22]
- Change the black shadow under every box to a lower opacity for it to look less stark but still bring depth just not in a cut and dry way, to add more of a flow to each boxed section. Same for the black liner seperating the menu section from the rest of the page.

**Comment by Jaeiya** [comment]
This is an interesting suggestion; I'll play around with it and see if we can strike a nice balance.

**Comment by Jaeiya** [comment]
Completed in https://github.com/Everything-Explained/web-client/commit/4e941b097006457e7ccc372b006335da5a0c9613
