### ISSUE TITLE
Remove shadow from menu icon

### ISSUE THREAD

**Issue by keybatte** [Everything-Explained/web-client#23]
-  try removing shadow from the menu icon and making it a tad biy of a lighter grey than the scroll bar. For it to stand out a bit more.

**Comment by Jaeiya** [comment]
I'll give this one a go and see how it looks. The reason I put the drop-shadow is because it wasn't standing out very well. Do you have something against the drop-shadow specifically? Or do you just like flat styles?

**Comment by keybatte** [comment]
Drop shadows look best when they are super super subtle imo I suppose. When they are more noticable, they make a font or icon dated. It is something I learned from making book covers, posters, banners etc for years⭐

**Comment by keybatte** [comment]
> I'll give this one a go and see how it looks. The reason I put the drop-shadow is because it wasn't standing out very well. Do you have something against the drop-shadow specifically? Or do you just like flat styles?

**Comment by Jaeiya** [comment]
Completed.
