### ISSUE TITLE
Change red color to darker wine or burgundy

### ISSUE THREAD

**Issue by keybatte** [Everything-Explained/web-client#25]
- Try Changing the bright wine Red details in menu and Everything Explained to a darker, more refined wine or burgundy red.

**Comment by Jaeiya** [comment]
Ethan was the one who picked out the red color, so I'll move this to the black box if his opinion decides to change on that. I, personally (as well as Ethan) like the intensity of it, but if it proves to be a problem for other users, we can address that.

It's definitely a valid concern.
