### ISSUE TITLE
Use signature font for blog header (if/when available)

### ISSUE THREAD

**Issue by keybatte** [Everything-Explained/web-client#26]
- For the Main blog title, the big header, and the quotes used in a blog, Use the Signiture font. Every other font used in website (rest of the headers and paragraphs) just use the same font, since the diffent sizes already bring variation. (In marketing and design A maximum of three fonts should be used. Four or higher starts to look chaotic and unpolished. That why I suggest just the Signiture and Default font)

**Comment by Jaeiya** [comment]
There are only 2 fonts in use, the header and the default font. Until we decide on a signature font, I'll move this to the ice box.

**Comment by Jaeiya** [comment]
Gonna black-box this for now as Ethan currently doesn't mind that the website has a different header font.
