### ISSUE TITLE
Revamp Red33m page with passcode and invite form

### ISSUE THREAD

**Issue by Jaeiya** [Everything-Explained/web-client#32]
## Why
**Passcode**
Instead of hiding the route entirely, which is still technically discoverable if someone is savvy enough, there needs to be a proper navigation guard that prevents access to the pages source code; this will allow it to be completely hidden from everyone until they have the passcode.

**Invite Form**
Given the nature of the information on the site, people will trend spiritually certain directions and potentially stumble upon the need for Red33m teachings, so if someone (who may not be known) stumbles upon the site, it would be nice to give them a chance to have access to what they need; it may be exactly what they were looking for.

## Process
**Passcode**
~This will be a simple plain-text code on the server. It doesn't need to be hidden beneath layers of encryption as I can't imagine anyone (at least right now) wanting this information so badly that they'd hack the server for it; which would be incredibly difficult to begin with.~
I will use bcrypt to encrypt the passcode as it requires almost no effort on the servers part. I realized storing passwords or codes in plain-text format just encourages people to figure them out.

**Invite Form**
@ethankahn98 can figure out the criteria necessary to build the form, which can then be validated and sent to his email or our organizations email (in the future).

**Menu**
Because Red33m teachings will be covered not only through video, but also literature, it should have its own header on the menu, alongside the new **Library** section. Just like the library section, it should have its own **videos** and **literature** links.

## Layout
* Present the passcode entry form
* If user doesn't have a passcode, they can click the "don't have a passcode" link.
* The link will present them with an invite form they can submit for review.

**Comment by ethankahn98** [comment]
**EC Form**

This form functions as an application for access to exclusive content. It is by no means a test for a single specific type of personality, intelligence, or level of advancement in spirituality. 

Please read carefully and then fill-out the form. 
Our team keeps this content exclusive for various significant reasons: 

1. It can be especially toxic for those pursuing Enlightenment. 

2. It can be exceedingly difficult to understand even for those who have undergone high-level Awakenings. It’s **guaranteed** to be misunderstood and mis-contextualized by anyone who doesn’t at least have a conceptual understanding of Enlightenment. Understanding Enlightenment is a pre-requisite. 

3. The content is overtly illogical & contradictory. Distributing logically-dissonant information like this puts the distributor in an unbalanced and potentially dangerous position of power that must be accounted for responsibly. 

4. The topics discussed are unverifiable even through spiritual methods, let alone scientific evidence. This makes the distributor similar to an unquestionable religious authority and they absolutely will not supplant themselves in such a position publicly. 

5. Before going unlisted, this content had about 30 initial subscribers and two of them openly contemplated suicide. 1/15 is too irresponsible a risk. 

6. This content can solicit deep existential crises but those weren’t the reason for the suicidal thoughts. It provides very compelling information about the hereafter that can make some people desire to go there as soon as possible and see very little reason to stay. 

7. You may have a more difficult time finding purpose in life after viewing this material. For some, the content has left them feeling adrift while for others, it’s been credited as having “saved their lives.” This content is very extreme in that manner. It either greatly helps or hurts. 

8. We feel that we should only choose to distribute this content to those who will find priceless value in it so as to not bring anyone harm. 

This form will determine if you’re more or less likely to gain value from the exclusive content. Please respond to the questions in an honest manner. 

Do not place responses that are intended to make you seem more advanced or Enlightened. This isn’t necessarily a test and even if you’re very Enlightened, it doesn’t mean that this content is going to be beneficial. 

This application is meant to gauge you on: 
1. Your understanding of Enlightenment (not necessarily about how Enlightened you are). 
2. Your flexibility in entertaining different concepts and your reasons for entertaining them. 
3. Your mental fortitude. 
4. Your religious inclinations. 
5. Your spiritual inclinations and your application of them in life. 

Please fill-out the form: 

1. What is your definition of Enlightenment (what does it mean to be Enlightened)? 
2. Do you find the pursuit of Enlightenment to be spiritually beneficial? If so, what benefits can Enlightenment provide to spiritual practitioners and those in their life? 
3. Do you think there are any **cons** to Enlightenment or is it all **pros**? 
4. Do you think the ego should be regarded as real or illusory? Should it be cultivated or unrealized? 
5. Do you think that egoic desires can be good or are they problematic by nature? Does the ego provide any beneficial functions or is it inherently-destructive? 

Thank you for your responses. Our team will get back to you as soon as possible. Whatever the results may be, do not take them personally. Ethan is friends with some of the most Enlightened people on the planet. He’s shared this exclusive content with some of them and even they have not all found it beneficial. Negative results should not be taken as a negative reflection on you.
