### ISSUE TITLE
Add Library page

### ISSUE THREAD

**Issue by Jaeiya** [Everything-Explained/web-client#34]
All video and articles should be compartmentalized within this page to allow easy access to our repository of information, including but not limited to...videos, literature, podcasts, etc...

## Structure
* Catalogue
  * Videos
    * Enlightenment
    * Love
    * Religion
  * Literature (example -- N/A at this time)
  * Podcasts (example -- N/A at this time)
  
## Data
* Each category should be loaded with a separate data request
  * data should be cached
* If possible, generate categories dynamically without needing to write any code. I could possible use our CMS to create a folder structure which gets built when a video/essay is created.

**Comment by ethankahn98** [comment]
General Spirituality (Meta-Spirituality) 
Enlightenment 
Religious Acceptance 
Philosophical Reasoning 
Reincarnation & the Soul 
Paranormal abilities 
PAT (Paranormal Ability Training) 
Paranormal Entities 
Psychedelics 
Law of Attraction 
Lifestyle Integration 
Conspiracies
