### ISSUE TITLE
Add "Support Us" page

### ISSUE THREAD

**Issue by Jaeiya** [Everything-Explained/web-client#44]
We should have a page dedicated to all the possible ways our users can support us, whether that's moniterily, through their affiliated services, or via direct content-contribution.

**Comment by ethankahn98** [comment]
Our team is committed to bringing you top-grade content for no cost at all. Furthermore, you - the customer - are granted the freedom to help us steer this platform. 

If there’s anything you’d like to see our community accomplish, consider giving back to the providers. 

Donations can contribute to a variety of matters including but not limited to: upgraded video-producing equipment; community out-reach programs (e.g. spiritual counseling, academic collaboration, providing for the underprivileged etc.); entrepreneurship; seminars; research; documentaries; podcast production etc. 

Even if you’d simply like to help our contributors make a living through producing more content, your support furthers that possibility. 

If any single one of these communal benefits appeals to your vision, then consider becoming one of our beloved benefactors! 

Support our organization on patreon: https://www.patreon.com/user?u=10855808&fan_landing=true

Donations of any amount are highly appreciated and you can trust our commitment to create the transformations you’re passionate about! 

Think you’ve got something of significant value and want to produce your own content for the community? Click the link below and shoot us a message. We’re excited to see what you can bring to the table! 
(insert link here)

Have the urge to collaborate with a member of the team? Click this link and give yourself the chance to make it happen! 
(insert link here)

Did you see something posted in an article or video that you felt inaccurately represented your organization or area of expertise? Go to this link and let us know what we need to correct. 
(insert link here)

Thank you all for your support in keeping this content high-quality!

**Comment by ethankahn98** [comment]
**Form for potential members**

Preferred Name or Title

1. What about our organization interests you?

2. In what specific ways do you envision yourself contributing to this community? Feel free to explain any of your talents or skills and how you’d utilize them to the fullest. 

**Form for potential collaborators** 

Preferred Name or Title

1. Which member(s) would you like to collaborate with and why?

2. What does your collaboration require of that/those member(s)? 

**Form for informative or corrective means** 

Preferred Name or Title

1. What group, institution, organization, or field of expertise are you speaking on behalf of? 

2. What specific issue(s) would you like to address?
